# Generated by Django 4.2.4 on 2023-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=75)),
                ('phone_No', models.CharField(max_length=13)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
